version: '2'

services:

  #  The Application
  app:
    container_name: laravel_igl
    build:
      context: ./
      dockerfile: development/app.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"


      # The Web Server
  web:
    container_name: nginx_server_igl
    build:
      context: ./
      dockerfile: development/web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    ports:
      - 80:80

      # The Database
  database:
    container_name: mysql_database_igl
    image: mysql
    environment:
      - "MYSQL_DATABASE=igl_project"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    ports:
      - 3306:3306
         # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata:



